services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ecobin-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - ecobin-network

    nginx:
        image: nginx:alpine
        container_name: ecobin-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - ecobin-network

    db:
        image: postgres:15
        container_name: ecobin-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ecobin
            POSTGRES_USER: ecobin
            POSTGRES_PASSWORD: ecobin
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - ecobin-network

networks:
    ecobin-network:
        driver: bridge

volumes:
    postgres_data:
